# Generated by Django 4.2.7 on 2023-11-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0002_alter_projects_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
